# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import financial_pb2 as financial__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in financial_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FinancialExtractorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractAndAnalyze = channel.unary_stream(
                '/financial.FinancialExtractor/ExtractAndAnalyze',
                request_serializer=financial__pb2.AnalyzeRequest.SerializeToString,
                response_deserializer=financial__pb2.AnalyzeResponse.FromString,
                _registered_method=True)


class FinancialExtractorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExtractAndAnalyze(self, request, context):
        """Server-side streaming: 1 Request -> Banyak Response (Progress + Hasil)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinancialExtractorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractAndAnalyze': grpc.unary_stream_rpc_method_handler(
                    servicer.ExtractAndAnalyze,
                    request_deserializer=financial__pb2.AnalyzeRequest.FromString,
                    response_serializer=financial__pb2.AnalyzeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'financial.FinancialExtractor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('financial.FinancialExtractor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinancialExtractor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExtractAndAnalyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/financial.FinancialExtractor/ExtractAndAnalyze',
            financial__pb2.AnalyzeRequest.SerializeToString,
            financial__pb2.AnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
