# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: financial.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'financial.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66inancial.proto\x12\tfinancial\"g\n\x0e\x41nalyzeRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\x12\x16\n\x0e\x66ile_extension\x18\x03 \x01(\t\x12\x14\n\x0c\x61nalyze_mode\x18\x04 \x01(\t\"\x95\x01\n\x0f\x41nalyzeResponse\x12\x15\n\x0blog_message\x18\x01 \x01(\tH\x00\x12\x16\n\x0cpartial_json\x18\x02 \x01(\tH\x00\x12\x30\n\nfinal_data\x18\x03 \x01(\x0b\x32\x1a.financial.FinancialResultH\x00\x12\x17\n\rerror_message\x18\x04 \x01(\tH\x00\x42\x08\n\x06result\"\xdb\x01\n\x0f\x46inancialResult\x12\x14\n\x0cnama_entitas\x18\x01 \x01(\t\x12\x17\n\x0fperiode_laporan\x18\x02 \x01(\t\x12\x11\n\tmata_uang\x18\x03 \x01(\t\x12\x14\n\x0csatuan_angka\x18\x04 \x01(\t\x12\x12\n\ntotal_aset\x18\x05 \x01(\x01\x12\x18\n\x10total_liabilitas\x18\x06 \x01(\x01\x12\x15\n\rtotal_ekuitas\x18\x07 \x01(\x01\x12\x13\n\x0blaba_bersih\x18\x08 \x01(\x01\x12\x16\n\x0ejson_data_lain\x18\t \x01(\t2b\n\x12\x46inancialExtractor\x12L\n\x11\x45xtractAndAnalyze\x12\x19.financial.AnalyzeRequest\x1a\x1a.financial.AnalyzeResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'financial_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=30
  _globals['_ANALYZEREQUEST']._serialized_end=133
  _globals['_ANALYZERESPONSE']._serialized_start=136
  _globals['_ANALYZERESPONSE']._serialized_end=285
  _globals['_FINANCIALRESULT']._serialized_start=288
  _globals['_FINANCIALRESULT']._serialized_end=507
  _globals['_FINANCIALEXTRACTOR']._serialized_start=509
  _globals['_FINANCIALEXTRACTOR']._serialized_end=607
# @@protoc_insertion_point(module_scope)
